FROM node:20-alpine AS builder

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
ARG VITE_ROUTER_MODE=history
ARG VITE_DEPLOY_TO_SERVER
ARG VITE_AMAP_KEY
ARG VITE_AMAP_SECURITY_CODE
ARG VITE_SENTRY_DSN
ARG VITE_SENTRY_ENVIRONMENT=production
ARG VITE_SENTRY_RELEASE
ARG SENTRY_AUTH_TOKEN
ARG SENTRY_ORG
ARG SENTRY_PROJECT
ARG SENTRY_RELEASE
RUN VITE_ROUTER_MODE="${VITE_ROUTER_MODE}" \
  VITE_DEPLOY_TO_SERVER="${VITE_DEPLOY_TO_SERVER}" \
  VITE_AMAP_KEY="${VITE_AMAP_KEY}" \
  VITE_AMAP_SECURITY_CODE="${VITE_AMAP_SECURITY_CODE}" \
  VITE_SENTRY_DSN="${VITE_SENTRY_DSN}" \
  VITE_SENTRY_ENVIRONMENT="${VITE_SENTRY_ENVIRONMENT}" \
  VITE_SENTRY_RELEASE="${VITE_SENTRY_RELEASE}" \
  SENTRY_AUTH_TOKEN="${SENTRY_AUTH_TOKEN}" \
  SENTRY_ORG="${SENTRY_ORG}" \
  SENTRY_PROJECT="${SENTRY_PROJECT}" \
  SENTRY_RELEASE="${SENTRY_RELEASE}" \
  pnpm build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
