sonar.projectKey=person-home
sonar.projectName=person-home
sonar.organization=merry-9001
sonar.sourceEncoding=UTF-8

sonar.sources=src,scripts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,src/posts/**,public/articles/**,yuque.json
